### ISSUE TITLE
Package breaking in El Capitan

### ISSUE THREAD

**Issue by vikashbajaj** [jaredks/rumps#47] opened 2015-10-08 06:59 UTC
getting this error after updating to EL Capitan(OSX 10.11)

```
Traceback (most recent call last):
  File "maccontrol.py", line 42, in <module>
  app.run()
  File "/Users/bajaj/MacControl/env/lib/python2.7/site-packages/rumps/rumps.py", line 1059, in run
    NSUserNotificationCenter.defaultUserNotificationCenter().setDelegate_(self._nsapp)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'
```

**Comment by abyx** [comment] 2015-12-15 06:05
:+1:

**Comment by scottydelta** [comment] 2016-04-12 23:05
works if run outside `virtualenv`

**Comment by Cabalist** [comment] 2016-06-08 01:49
Yep.  Pyobjc doesn't like virtualenv.  :/

**Comment by waldo1979** [comment] 2016-08-09 16:21
You can resolve this issue by adding a Info.plist to the directory where your python binary is. For example:
$ echo $PYENV_ROOT
/usr/local/var/pyenv
$ cat .python-version 
hoptray
$ cd /usr/local/var/pyenv/versions/hoptray/bin
$ /usr/libexec/PlistBuddy -c 'Add :CFBundleIdentifier string "org.python.python"' Info.plist

**Comment by Cabalist** [comment] 2016-08-09 19:38
Interesting @waldo1979.   I really want this to be true.  :) Could you tell me a little more about your environment?  I don't have a $PYENV_ROOT set or a .python-version file.   

I think I get the same path by doing `which python`.  This gets me: `/Users/work/.virtualenvs/dashwaretest/bin/python`

Then when I add the Info.plist to this directory I get the same error.

**Comment by Cabalist** [comment] 2016-08-09 21:18
I take that back.  It is now running in a 2.7 virtualenv.  Very nice.  :)

**Comment by jaredks** [comment] 2016-12-24 22:16
Duplicate of https://github.com/jaredks/rumps/issues/9

**Closed by jaredks** 2016-12-24 22:16 UTC
