### ISSUE TITLE
Update/fix pip install

### ISSUE THREAD

**Issue by DanielNoord** [jaredks/rumps#158] opened 2021-04-17 16:25 UTC
Not sure what is wrong with the install but running `pip3 install rumps` does not install the version that is currently on the master branch.
This is crucial as the version downloaded by pip is missing `notifications.py` which fixes notifications on newer versions of OS X.

**Comment by nkantar** [comment] 2022-09-29 16:54
This is effectively a duplicate of #173.

**Closed** 2022-10-03 23:35 UTC
