### ISSUE TITLE
Notification does not work (with mac 10.12.2)? 

### ISSUE THREAD

**Issue by hunkim** [jaredks/rumps#59] opened 2017-01-05 13:21 UTC
I tested the simple example in readme. It seems the notification does not work in my mac.

**Comment by withzombies** [comment] 2017-01-25 20:24
I get this error:

```python
>>> rumps.notification("Example Title", "Example subtitle", "Example text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/rumps/rumps.py", line 96, in notification
    notification.setUserInfo_({} if data is None else data)
objc.error: NSInvalidUnarchiveOperationException - Class 'OC_PythonDictionary' has a superclass that supports secure coding, but 'OC_PythonDictionary' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant.
```

**Comment by toaster** [comment] 2017-01-28 10:08
When commenting out the line 96 in `rumps.py` you will loose the user data support but also have working notifications again. For me it is good enough as workaround until the problem is fixed.

**Comment by toaster** [comment] 2017-01-28 10:48
*Update*: For some reason this only works when not running an application :(. So it is no usable workaround.

**Comment by chekunkov** [comment] 2017-03-03 15:30
In the pyobjc master branch contains a [change](https://bitbucket.org/ronaldoussoren/pyobjc/commits/dfd78b4cd6f3#chg-pyobjc-core/NEWS.txt) that marks python dict as not supporting secure coding and attempt to use rumps notifications throws another exception:

```
Traceback (most recent call last):
  File "...", line 132, in ...
    rumps.notification("Error", "", "Something failed, check errors log")
  File "/Users/alex/.virtualenvs/instalike/lib/python2.7/site-packages/rumps/rumps.py", line 96, in notification
    notification.setUserInfo_({} if data is None else data)
error: NSInvalidUnarchiveOperationException - Class 'OC_PythonDictionary' disallows secure coding. It must return YES from supportsSecureCoding.
```

There's also some related discussion in https://bitbucket.org/ronaldoussoren/pyobjc/pull-requests/12

**Comment by pythonios** [comment] 2017-03-08 08:18
Are there any solutions for this issue?

**Comment by chekunkov** [comment] 2017-03-08 12:04
I have a workaround, not a solution:

```
import objc
import rumps

NSDictionary = objc.lookUpClass("NSDictionary")
rumps.notification("Error", "", "Something failed", data=NSDictionary())
```

IMO correct solution would be to recursively convert data `dict` to a `NSMutableDictionary` inside the `rumps.notification`, but I haven't found a way to do that using standard pyobjc utilities - there's a `propertyListFromPythonCollection` but it doesn't convert values, which, again, causes the error if `dict` values are Python objects (e.g. strings). I have my problem fixed by the workaround above anyway, so I stopped there.

**Comment by LinxiFan** [comment] 2017-04-09 05:54
Notification doesn't work in Mac OS X **10.12.1** as well. @chekunkov the workaround fails when the application is running.

**Comment by chekunkov** [comment] 2017-04-09 09:44
@LinxiFan sorry, I'm on macOS *10.12.4* and cannot test the workaround on an older version. In my case this workaround is used with an empty `NSDictionary()` as a `data`, it should work if you pass NS\* objects as keys/values to the dictionary, it will fail if you pass standard Python objects there.

You didn't share an example and traceback, so only you know what values you pass there and have a traceback - try to debug it.

**Comment by acnebs** [comment] 2017-04-30 22:10
@chekunkov I am also on macOS 10.12.4, and your workaround is not working for me. No error, just fails silently. The code I used is exactly your own, but for completeness sake:

`    
@rumps.clicked("Notitest")
    def noti(self, _):
        NSDictionary = objc.lookUpClass("NSDictionary")
        rumps.notification("Title", "Subtitle", "Test", data=NSDictionary())
`

**Comment by notdaniel** [comment] 2017-05-11 23:02
I can confirm silent failure on 10.12.4, with the above workaround having no effect.

**Comment by KuDeTa** [comment] 2017-08-15 18:17
Not working in 10.12.5 either - any chance of a fix or workaround?

**Comment by L3rchal** [comment] 2017-08-27 16:28
Same on 10.12.6 *sight* fix would be great

**Comment by tobx** [comment] 2017-11-16 08:56
Same as withzombies on 10.13.1.

**Comment by vbauer** [comment] 2018-03-14 20:08
Same problem with 10.13.3

**Comment by geeknam** [comment] 2018-05-15 08:07
Others might consider using pync for notifications. Works well within timers too.

**Closed** 2018-11-28 01:16 UTC
